# RENAME THIS FILE TO settings.yaml

# Sample settings file. Exclude from version control as it contains secrets.
# For more information follow the tutorial:
# https://173tech.github.io/sayn/tutorials/tutorial_part1

# Profiles are useful when you have multiple environments (ie: for testing and production)
# The profiles indicate which credentials and parameter values to use for each profile
# Credentials are defined at the end of the settings.yaml file
profiles:
  dev:
    credentials:
      # All required credentials defined in the project.yaml need to be linked
      # to specific credential in the final section of this file
      warehouse: dev_db
    parameters:
      # We use a user_prefix on dev to separate tables with prod
      user_prefix: yoda_
  prod:
    credentials:
      warehouse: prod_db

# The profile can be changed with the -p option when running sayn commands
# Example: sayn run -p prod
default_profile: dev

credentials:
  dev_db:
    type: sqlite
    database: dev.db
  prod_db:
    type: sqlite
    database: prod.db
